const jobs=[
  {
    "id": 1,
    "company": "Photosnap",
    "logo":require("./images/photosnap.svg").default,
    "new": true,
    "featured": true,
    "position": "Senior Frontend Developer",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "USA Only",
    "languages": ["Frontend", "Senior","HTML", "CSS", "JavaScript"],
    "tools": []
  },
  {
    "id": 2,
    "company": "Manage",
    "logo": require("./images/manage.svg").default,
    "new": true,
    "featured": true,
    "position": "Fullstack Developer",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Remote",
    "languages": ["Fullstack", "Midweight","Python", "React"],
  },
  {
    "id": 3,
    "company": "Account",
    "logo": require("./images/account.svg").default,
    "new": true,
    "featured": false,
    "position": "Junior Frontend Developer",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "USA Only",
    "languages": ["Frontend", "Junior","JavaScript", "React", "Sass"],
  },
  {
    "id": 4,
    "company": "MyHome",
    "logo": require("./images/myhome.svg").default,
    "new": false,
    "featured": false,
    "position": "Junior Frontend Developer",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "USA Only",
    "languages": ["Frontend", "Junior","CSS", "JavaScript"]
  },
  {
    "id": 5,
    "company": "Loop Studios",
    "logo": require("./images/loop-studios.svg").default,
    "new": false,
    "featured": false,
    "position": "Software Engineer",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Worldwide",
    "languages": ["Fullstack", "Midweight", "JavaScript", "Ruby", "Sass"],
  },
  {
    "id": 6,
    "company": "FaceIt",
    "logo": require("./images/faceit.svg").default,
    "new": false,
    "featured": false,
    "position": "Junior Backend Developer",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "UK Only",
    "languages": ["Backend", "Junior", "Ruby", "RoR"],
  },
  {
    "id": 7,
    "company": "Shortly",
    "logo": require("./images/shortly.svg").default,
    "new": false,
    "featured": false,
    "position": "Junior Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Worldwide",
    "languages": ["Frontend", "Junior", "HTML", "JavaScript", "Sass"],
  },
  {
    "id": 8,
    "company": "Insure",
    "logo": require("./images/insure.svg").default,
    "new": false,
    "featured": false,
    "position": "Junior Frontend Developer",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "USA Only",
    "languages": ["Frontend", "Junior","JavaScript", "Vue", "Sass"],
  },
  {
    "id": 9,
    "company": "Eyecam Co.",
    "logo": require("./images/eyecam-co.svg").default,
    "new": false,
    "featured": false,
    "position": "Full Stack Engineer",
    "postedAt": "3w ago",
    "contract": "Full Time",
    "location": "Worldwide",
    "languages": ["Fullstack", "Midweight", "JavaScript", "Python", "Django"],
  },
  {
    "id": 10,
    "company": "The Air Filter Company",
    "logo": require("./images/the-air-filter-company.svg").default,
    "new": false,
    "featured": false,
    "position": "Front-end Dev",
    "postedAt": "1mo ago",
    "contract": "Part Time",
    "location": "Worldwide",
    "languages": ["Frontend", "Junior", "JavaScript", "React", "Sass"]
  }
]

export default jobs;